# Generated by Django 3.2.13 on 2022-07-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
