[tool.poetry]
name = "notesapi"
version = "0.1.0"
description = ""
authors = ["rubbie kelvin <dev.rubbie@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
psycopg2-binary = "^2.9.3"
autopep8 = "^1.6.0"
graphene-django = "^2.15.0"
Django = "<4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
