// Autogenerated by "/home/rubbiekelvin/Projects/notes/cli/theme-generator/main.py"
/** @type {import('tailwindcss').Config} */

module.exports = {
  "content": [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}"
  ],
  "theme": {
    "fontFamily": {
      "sans": "Google Sans"
    },
    "extend": {
      "colors": {
        "themed-bg": "var(--themed-bg)",
        "themed-bg-elevated": "var(--themed-bg-elevated)",
        "themed-text": "var(--themed-text)",
        "themed-text-subtle": "var(--themed-text-subtle)",
        "themed-stroke": "var(--themed-stroke)",
        "themed-stroke-light": "var(--themed-stroke-light)",
        "themed-hover-bg": "var(--themed-hover-bg)",
        "themed-active-bg": "var(--themed-active-bg)",
        "themed-hover-text": "var(--themed-hover-text)",
        "themed-hover-text-subtle": "var(--themed-hover-text-subtle)",
        "themed-accent-bg": "var(--themed-accent-bg)",
        "themed-accent-text": "var(--themed-accent-text)",
        "themed-accent-hover-bg": "var(--themed-accent-hover-bg)",
        "themed-accent-active-bg": "var(--themed-accent-active-bg)",
        "themed-accent-hover-text": "var(--themed-accent-hover-text)",
        "themed-accent-hover-text-subtle": "var(--themed-accent-hover-text-subtle)"
      }
    }
  },
  "plugins": []
}
