# Generated by Django 4.1.3 on 2022-12-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_managers_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='readable_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
