# Generated by Django 4.1.5 on 2023-01-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
