# Generated by Django 4.1.6 on 2023-02-13 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_edit', models.BooleanField(default=False)),
                ('shared_on', models.DateTimeField(auto_now_add=True)),
                ('content', models.JSONField(default=None, help_text='Users can edit shared notes, but note directly on the main notes app', null=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='api.note')),
                ('shared_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_accesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
