# Generated by Django 4.1.6 on 2023-02-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_sharednote'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sharednote',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('shared_to', 'note'), name='share_note_to_user_once'),
        ),
    ]
