# Generated by Django 4.1.7 on 2023-02-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_tag_alter_note_content_alter_note_id_tagmembership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
