# Generated by Django 4.1.7 on 2023-02-26 16:02

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_tag_color_alter_tag_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_active_for', models.ManyToManyField(related_name='targeted_active_features', to=settings.AUTH_USER_MODEL)),
                ('is_inactive_for', models.ManyToManyField(related_name='targeted_inactive_features', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
