# Generated by Django 4.1.7 on 2023-02-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='allow_anon',
            field=models.BooleanField(default=True),
        ),
    ]
