# Generated by Django 4.1.7 on 2023-02-26 20:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_feature_allow_anon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='is_active_for',
            field=models.ManyToManyField(blank=True, related_name='targeted_active_features', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feature',
            name='is_inactive_for',
            field=models.ManyToManyField(blank=True, related_name='targeted_inactive_features', to=settings.AUTH_USER_MODEL),
        ),
    ]
