# Generated by Django 4.1.7 on 2023-03-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_feature_is_active_for_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagmembership',
            name='note',
        ),
        migrations.RemoveField(
            model_name='tagmembership',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='TagMembership',
        ),
    ]
