export const OPTIONS = {
    DEFAULT: 'DEFAULT',
    ALPHABETICAL: 'ALPHABETICAL',
    DATE_CREATED: 'DATE_CREATED',
    DATE_EDITED: 'DATE_EDITED', 
}

export const ORDER = {
    ACSENDING: 'ACSENDING',
    DESCENDING: 'DESCENDING'
}