# Generated by Django 4.1.1 on 2022-09-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_folder_note_tag_shared_note_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shared',
            old_name='date_shared',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='folder',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shared',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shared',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('name', 'is_deleted', 'owner'), name='unique_folder_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(fields=('title', 'is_deleted', 'author'), name='unique_note_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name', 'is_deleted', 'author'), name='unique_tag_name_per_user'),
        ),
    ]
