# Generated by Django 3.2.13 on 2022-05-21 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ld', models.UUIDField()),
                ('name', models.CharField(max_length=40)),
                ('folder', models.CharField(default=None, max_length=999, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField()),
                ('body', models.JSONField()),
                ('private', models.BooleanField(default=True)),
                ('public_slug', models.SlugField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
