# Generated by Django 3.2.13 on 2022-05-22 08:00

import apps.note.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.JSONField(default=apps.note.models.default_note_body),
        ),
    ]
